# ビルド環境
FROM node:10.24.1-alpine as build-stage
WORKDIR /app
COPY client/package*.json ./
COPY client .
RUN npm run build

# 本番環境
FROM nginx:1.14.0-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
