---
version: "3.6"
services:
  train:
    image: opennmt/opennmt:latest
    volumes:
      - ./data:/data

  rest:
    image: opennmt/opennmt:latest
    volumes:
      - ./data:/data
    command: th tools/rest_translation_server.lua -config /data/rest.yml
    ports:
      - 7784:7784

  0mq:
    image: opennmt/opennmt:latest
    volumes:
      - ./data:/data
    command: th tools/translation_server.lua -config /data/0mq.yml
    ports:
      - 5556:5556
