---
version: "3.6"
services:
  train:
    image: opennmt/opennmt:latest
    volumes:
      - ./data:/data

  zmqrep:
    image: opennmt/opennmt:latest
    volumes:
      - ./data:/data
    command: th tools/translation_server.lua -config /data/zmqrep.yml

  zmqreq:
    env_file:
      - ./zmqreq/.env
    image: opennmt/zmqreq:latest
    build:
      context: ./zmqreq
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
      - ./zmqreq:/usr/src/app
    command: python api.py --port 8080 --host 0.0.0.0 --debug true
    ports:
      - 8080:8080
    depends_on:
      - zmqrep

  frontend:
    env_file:
      - ./frontend/.env
    image: opennmt/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/home/node/frontend
    working_dir: /home/node/frontend/app
    command: yarn
    ports:
      - 8081:8081
    depends_on:
      - zmqreq
